server:
  port: 8080

spring:
  application:
    name: clickhouse-tx-demo
  
  # ClickHouse 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    click:
      driverClassName: com.clickhouse.jdbc.ClickHouseDriver
      # 改成 test 库
      url: jdbc:clickhouse://localhost:8123/test?compress=0
      username: admin
      password: admin123
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000

# MyBatis Plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.clickhouse.entity
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
